name: gulp

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install & Gulp
      run: |
        npm i gulp gulp-terser gulp-minify-css -D && npx gulp
        gulp 
        
    - name: Commit
      run: |
        git config --global user.email yfun-bot@github.com
        git config --global user.name YFun's Bot
        git add . 
        git commit -m ":zap: Successful minify" -a
        
    - name: Push
      run: |
        git push origin main -f